apiVersion: v1
kind: Service
metadata:
  name: face-recog
spec:
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  selector:
    app: face-recog
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: face-recognition-pvc-unknown
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: face-recognition-pvc-known
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: face-recognition-pv-unknown
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: local-storage
  local:
    path: /unknown_people
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: local-pvc
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: face-recognition-pv-known
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: local-storage
  local:
    path: /known_people
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: local-pvc
              operator: In
              values:
                - "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-recog
spec:
  selector:
    matchLabels:
      app: face-recog
  replicas: 1
  template:
    metadata:
      labels:
        app: face-recog
    spec:
      containers:
        - name: face-recog
          image: ghcr.io/kube-project/face-recognition-service:v0.0.8
          ports:
            - containerPort: 50051
              hostPort: 50051
              name: face-recog
          env:
            - name: KNOWN_PEOPLE
              value: "/known_people"
          volumeMounts:
            - name: known-people-storage
              mountPath: /known_people
            - name: unknown-people-storage
              mountPath: /unknown_people
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "500m"
              memory: "1024Mi"
      volumes:
        - name: known-people-storage
          hostPath:
            path: /known_people
            type: Directory
        - name: unknown-people-storage
          hostPath:
            path: /unknown_people
            type: Directory