apiVersion: v1
kind: Service
metadata:
  name: face-recog
spec:
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
  selector:
    app: face-recog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-recog
spec:
  selector:
    matchLabels:
      app: face-recog
  replicas: 1
  template:
    metadata:
      labels:
        app: face-recog
    spec:
      containers:
      - name: face-recog
        image: ghcr.io/kube-project/face-recognition-service:v0.0.8
        ports:
        - containerPort: 50051
          hostPort: 50051
          name: face-recog
        env:
        - name: KNOWN_PEOPLE
          value: "/known_people"
        volumeMounts:
        - name: known-people-storage
          mountPath: /known_people
        - name: unknown-people-storage
          mountPath: /unknown_people
        resources:
          limits:
            cpu: "500m"
            memory: "1024Mi"
          requests:
            cpu: "500m"
            memory: "1024Mi"
      volumes:
      - name: known-people-storage
        hostPath:
          path: /known_people
      - name: unknown-people-storage
        hostPath:
          path: /unknown_people
