name: Release

on:
  push:
    tags:
      - '*-v*'

env:
  REGISTRY: ghcr.io
  # DOCKERFILE: ${{ github.workspace }}/goreleaser.dockerfile

jobs:
  release-frontend:
    name: Release Frontend
    if: startsWith(github.ref, 'refs/tags/frontend')
    runs-on: ubuntu-latest
    env:
      DOCKERFILE: ${{ github.workspace }}/frontend-service/goreleaser.dockerfile
    permissions:
      contents: 'write'
      id-token: 'write'
      pull-requests: 'read'
      repository-projects: 'write'
      packages: 'write'
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Prepare
      id: prep
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Run goreleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        distribution: goreleaser
        version: latest
        args: release --clean --timeout 60m --skip-validate --config=./.goreleaser.yaml --release-notes=docs/release_notes/${{ env.RELEASE_VERSION }}.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GORELEASER_CURRENT_TAG: ${{ env.RELEASE_VERSION }}

  release-receiver:
    name: Release Receiver
    if: startsWith(github.ref, 'refs/tags/receiver')
    runs-on: ubuntu-latest
    env:
      DOCKERFILE: ${{ github.workspace }}/receiver-service/goreleaser.dockerfile
    permissions:
      contents: 'write'
      id-token: 'write'
      pull-requests: 'read'
      repository-projects: 'write'
      packages: 'write'
    defaults:
      run:
        working-directory: ./receiver-service
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Prepare
      id: prep
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Run goreleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        distribution: goreleaser
        version: latest
        args: release --clean --timeout 60m --skip-validate --config=./.goreleaser.yaml --release-notes=docs/release_notes/${{ env.RELEASE_VERSION }}.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GORELEASER_CURRENT_TAG: ${{ env.RELEASE_VERSION }}

  release-image-processor:
    name: Trigger release build
    if: startsWith(github.ref, 'refs/tags/image-processor')
    runs-on: ubuntu-latest
    env:
      DOCKERFILE: ${{ github.workspace }}/image-processor-service/goreleaser.dockerfile
    permissions:
      contents: 'write'
      id-token: 'write'
      pull-requests: 'read'
      repository-projects: 'write'
      packages: 'write'
    defaults:
      run:
        working-directory: ./image-processor-service
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Prepare
      id: prep
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Run goreleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        distribution: goreleaser
        version: latest
        args: release --clean --timeout 60m --skip-validate --config=./.goreleaser.yaml --release-notes=docs/release_notes/${{ env.RELEASE_VERSION }}.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GORELEASER_CURRENT_TAG: ${{ env.RELEASE_VERSION }}
